window.SOS_LOW_TICKET_PRODUCTS = [
  {
    "id": "01",
    "title": "Do “qual o valor?” ao próximo passo",
    "family": "Scripts para WhatsApp",
    "familyKey": "scripts-whatsapp",
    "price": 27,
    "delivery": "Respostas que informam preço quando disponível e ajudam a entender a necessidade sem interrogatório",
    "buyer": "vendedor, autônomo ou dono que atende pelo WhatsApp",
    "image": "assets/01-scripts-whatsapp.png",
    "detailUrl": "itens/p01-do-qual-o-valor-ao-proximo-passo/",
    "checkoutUrl": null
  },
  {
    "id": "02",
    "title": "Enviei o orçamento. E agora?",
    "family": "Scripts para WhatsApp",
    "familyKey": "scripts-whatsapp",
    "price": 27,
    "delivery": "Mensagens para confirmar recebimento, esclarecer dúvidas, retomar e encerrar acompanhamento",
    "buyer": "vendedor, autônomo ou dono que atende pelo WhatsApp",
    "image": "assets/01-scripts-whatsapp.png",
    "detailUrl": "itens/p02-enviei-o-orcamento-e-agora/",
    "checkoutUrl": null
  },
  {
    "id": "03",
    "title": "Respostas para objeções",
    "family": "Scripts para WhatsApp",
    "familyKey": "scripts-whatsapp",
    "price": 27,
    "delivery": "Alternativas para preço, comparação, prazo, confiança e decisão compartilhada; sem pressão artificial",
    "buyer": "vendedor, autônomo ou dono que atende pelo WhatsApp",
    "image": "assets/01-scripts-whatsapp.png",
    "detailUrl": "itens/p03-respostas-para-objecoes/",
    "checkoutUrl": null
  },
  {
    "id": "04",
    "title": "Conversas que ficaram paradas",
    "family": "Scripts para WhatsApp",
    "familyKey": "scripts-whatsapp",
    "price": 27,
    "delivery": "Retomadas por motivo e contexto conhecido, com critérios para escolher quem contatar e quando parar",
    "buyer": "vendedor, autônomo ou dono que atende pelo WhatsApp",
    "image": "assets/01-scripts-whatsapp.png",
    "detailUrl": "itens/p04-conversas-que-ficaram-paradas/",
    "checkoutUrl": null
  },
  {
    "id": "05",
    "title": "Do “quero comprar” ao pedido confirmado",
    "family": "Scripts para WhatsApp",
    "familyKey": "scripts-whatsapp",
    "price": 27,
    "delivery": "Mensagens para resumir escolha, combinar entrega, orientar pagamento e confirmar o pedido conforme seu status real",
    "buyer": "vendedor, autônomo ou dono que atende pelo WhatsApp",
    "image": "assets/01-scripts-whatsapp.png",
    "detailUrl": "itens/p05-do-quero-comprar-ao-pedido-confirmado/",
    "checkoutUrl": null
  },
  {
    "id": "06",
    "title": "Atendimento em situações difíceis",
    "family": "Scripts para WhatsApp",
    "familyKey": "scripts-whatsapp",
    "price": 27,
    "delivery": "Respostas para atraso, indisponibilidade, erro e reclamação, com encaminhamento ao responsável",
    "buyer": "vendedor, autônomo ou dono que atende pelo WhatsApp",
    "image": "assets/01-scripts-whatsapp.png",
    "detailUrl": "itens/p06-atendimento-em-situacoes-dificeis/",
    "checkoutUrl": null
  },
  {
    "id": "07",
    "title": "Catálogo de bolso para WhatsApp",
    "family": "Apresentação comercial",
    "familyKey": "apresentacao-comercial",
    "price": 37,
    "delivery": "Páginas de produtos/serviços com fotos, descrição, preço, condições e próximo passo",
    "buyer": "prestador de serviço, pequeno comércio ou profissional independente",
    "image": "assets/02-apresentacao-comercial.png",
    "detailUrl": "itens/p07-catalogo-de-bolso-para-whatsapp/",
    "checkoutUrl": null
  },
  {
    "id": "08",
    "title": "Orçamento claro em uma página",
    "family": "Apresentação comercial",
    "familyKey": "apresentacao-comercial",
    "price": 37,
    "delivery": "Modelo com itens, escopo, prazo, validade, condições e aceite",
    "buyer": "prestador de serviço, pequeno comércio ou profissional independente",
    "image": "assets/02-apresentacao-comercial.png",
    "detailUrl": "itens/p08-orcamento-claro-em-uma-pagina/",
    "checkoutUrl": null
  },
  {
    "id": "09",
    "title": "Apresentação de três opções",
    "family": "Apresentação comercial",
    "familyKey": "apresentacao-comercial",
    "price": 37,
    "delivery": "Comparativo editável de versões essencial, intermediária e completa, com diferenças reais",
    "buyer": "prestador de serviço, pequeno comércio ou profissional independente",
    "image": "assets/02-apresentacao-comercial.png",
    "detailUrl": "itens/p09-apresentacao-de-tres-opcoes/",
    "checkoutUrl": null
  },
  {
    "id": "10",
    "title": "Portfólio com prova do trabalho",
    "family": "Apresentação comercial",
    "familyKey": "apresentacao-comercial",
    "price": 27,
    "delivery": "Estrutura de caso com problema, trabalho realizado, evidência autorizada e limites do resultado",
    "buyer": "prestador de serviço, pequeno comércio ou profissional independente",
    "image": "assets/02-apresentacao-comercial.png",
    "detailUrl": "itens/p10-portfolio-com-prova-do-trabalho/",
    "checkoutUrl": null
  },
  {
    "id": "11",
    "title": "Roteiros de áudios comerciais",
    "family": "Apresentação comercial",
    "familyKey": "apresentacao-comercial",
    "price": 47,
    "delivery": "Guias curtos para explicar preço, proposta e próximos passos sem gravar áudios longos",
    "buyer": "prestador de serviço, pequeno comércio ou profissional independente",
    "image": "assets/02-apresentacao-comercial.png",
    "detailUrl": "itens/p11-roteiros-de-audios-comerciais/",
    "checkoutUrl": null
  },
  {
    "id": "12",
    "title": "Demonstrações em vídeo pelo WhatsApp",
    "family": "Apresentação comercial",
    "familyKey": "apresentacao-comercial",
    "price": 37,
    "delivery": "Roteiros de gravação para produto, serviço e explicação de orçamento, com lista de cenas",
    "buyer": "prestador de serviço, pequeno comércio ou profissional independente",
    "image": "assets/02-apresentacao-comercial.png",
    "detailUrl": "itens/p12-demonstracoes-em-video-pelo-whatsapp/",
    "checkoutUrl": null
  },
  {
    "id": "13",
    "title": "Status do WhatsApp com intenção comercial",
    "family": "Conteúdo e campanhas",
    "familyKey": "conteudo-campanhas",
    "price": 47,
    "delivery": "Sequências editáveis de demonstração, dúvidas, bastidores e convite para conversar",
    "buyer": "dono de negócio, vendedor ou responsável por conteúdo",
    "image": "assets/03-conteudo-campanhas.png",
    "detailUrl": "itens/p13-status-do-whatsapp-com-intencao-comercial/",
    "checkoutUrl": null
  },
  {
    "id": "14",
    "title": "Campanha de uma oferta",
    "family": "Conteúdo e campanhas",
    "familyKey": "conteudo-campanhas",
    "price": 37,
    "delivery": "Roteiro de preparação, abertura, esclarecimento e encerramento, com peças e datas editáveis",
    "buyer": "dono de negócio, vendedor ou responsável por conteúdo",
    "image": "assets/03-conteudo-campanhas.png",
    "detailUrl": "itens/p14-campanha-de-uma-oferta/",
    "checkoutUrl": null
  },
  {
    "id": "15",
    "title": "Conteúdo a partir das dúvidas dos clientes",
    "family": "Conteúdo e campanhas",
    "familyKey": "conteudo-campanhas",
    "price": 47,
    "delivery": "Planilha para transformar perguntas reais em roteiros de conteúdo e chamadas para conversa",
    "buyer": "dono de negócio, vendedor ou responsável por conteúdo",
    "image": "assets/03-conteudo-campanhas.png",
    "detailUrl": "itens/p15-conteudo-a-partir-das-duvidas-dos-clientes/",
    "checkoutUrl": null
  },
  {
    "id": "16",
    "title": "Uma oferta, vários criativos",
    "family": "Conteúdo e campanhas",
    "familyKey": "conteudo-campanhas",
    "price": 67,
    "delivery": "Matriz de ângulos, roteiros de peças e ficha para registrar o teste",
    "buyer": "dono de negócio, vendedor ou responsável por conteúdo",
    "image": "assets/03-conteudo-campanhas.png",
    "detailUrl": "itens/p16-uma-oferta-varios-criativos/",
    "checkoutUrl": null
  },
  {
    "id": "17",
    "title": "Do anúncio à conversa",
    "family": "Conteúdo e campanhas",
    "familyKey": "conteudo-campanhas",
    "price": 47,
    "delivery": "Mapa preenchível ligando promessa, chamada, intenção esperada e primeira resposta",
    "buyer": "dono de negócio, vendedor ou responsável por conteúdo",
    "image": "assets/03-conteudo-campanhas.png",
    "detailUrl": "itens/p17-do-anuncio-a-conversa/",
    "checkoutUrl": null
  },
  {
    "id": "18",
    "title": "Parcerias locais e indicações profissionais",
    "family": "Conteúdo e campanhas",
    "familyKey": "conteudo-campanhas",
    "price": 27,
    "delivery": "Apresentação de parceria, roteiro de contato individual pertinente e quadro de acompanhamento",
    "buyer": "dono de negócio, vendedor ou responsável por conteúdo",
    "image": "assets/03-conteudo-campanhas.png",
    "detailUrl": "itens/p18-parcerias-locais-e-indicacoes-profissionais/",
    "checkoutUrl": null
  },
  {
    "id": "19",
    "title": "Confirmação de agendamentos",
    "family": "Agenda e atendimento",
    "familyKey": "agenda-servicos",
    "price": 37,
    "delivery": "Mensagens e rotina de confirmação com data, local, preparo fornecido pelo negócio e resposta esperada",
    "buyer": "negócio de serviços com horários marcados",
    "image": "assets/04-agenda-servicos.png",
    "detailUrl": "itens/p19-confirmacao-de-agendamentos/",
    "checkoutUrl": null
  },
  {
    "id": "20",
    "title": "Remarcação e cancelamento organizados",
    "family": "Agenda e atendimento",
    "familyKey": "agenda-servicos",
    "price": 37,
    "delivery": "Fluxos de conversa para escolher outra data, registrar motivo e esclarecer a política existente",
    "buyer": "negócio de serviços com horários marcados",
    "image": "assets/04-agenda-servicos.png",
    "detailUrl": "itens/p20-remarcacao-e-cancelamento-organizados/",
    "checkoutUrl": null
  },
  {
    "id": "21",
    "title": "Lista de espera para horários disponíveis",
    "family": "Agenda e atendimento",
    "familyKey": "agenda-servicos",
    "price": 27,
    "delivery": "Quadro de interessados, critérios de convite e mensagens que só oferecem disponibilidade confirmada",
    "buyer": "negócio de serviços com horários marcados",
    "image": "assets/04-agenda-servicos.png",
    "detailUrl": "itens/p21-lista-de-espera-para-horarios-disponiveis/",
    "checkoutUrl": null
  },
  {
    "id": "22",
    "title": "Conversa após uma falta",
    "family": "Agenda e atendimento",
    "familyKey": "agenda-servicos",
    "price": 47,
    "delivery": "Mensagens para compreender o ocorrido e oferecer reagendamento quando fizer sentido",
    "buyer": "negócio de serviços com horários marcados",
    "image": "assets/04-agenda-servicos.png",
    "detailUrl": "itens/p22-conversa-apos-uma-falta/",
    "checkoutUrl": null
  },
  {
    "id": "23",
    "title": "Da consulta inicial à proposta de serviço",
    "family": "Agenda e atendimento",
    "familyKey": "agenda-servicos",
    "price": 27,
    "delivery": "Ficha de descoberta e roteiro para resumir necessidade, solução proposta e próximo passo",
    "buyer": "negócio de serviços com horários marcados",
    "image": "assets/04-agenda-servicos.png",
    "detailUrl": "itens/p23-da-consulta-inicial-a-proposta-de-servico/",
    "checkoutUrl": null
  },
  {
    "id": "24",
    "title": "Primeira visita bem orientada",
    "family": "Agenda e atendimento",
    "familyKey": "agenda-servicos",
    "price": 27,
    "delivery": "Modelos de boas-vindas, localização, documentos necessários e instruções práticas",
    "buyer": "negócio de serviços com horários marcados",
    "image": "assets/04-agenda-servicos.png",
    "detailUrl": "itens/p24-primeira-visita-bem-orientada/",
    "checkoutUrl": null
  },
  {
    "id": "25",
    "title": "Acompanhamento depois da compra",
    "family": "Pós-venda e relacionamento",
    "familyKey": "pos-venda",
    "price": 37,
    "delivery": "Sequência de checagem de recebimento, uso inicial e necessidade de ajuda",
    "buyer": "negócio que já possui clientes e quer cuidar da continuidade",
    "image": "assets/05-pos-venda.png",
    "detailUrl": "itens/p25-acompanhamento-depois-da-compra/",
    "checkoutUrl": null
  },
  {
    "id": "26",
    "title": "Pedido de avaliação e depoimento",
    "family": "Pós-venda e relacionamento",
    "familyKey": "pos-venda",
    "price": 47,
    "delivery": "Mensagens para solicitar relato honesto e autorização de uso; sem fabricar avaliações",
    "buyer": "negócio que já possui clientes e quer cuidar da continuidade",
    "image": "assets/05-pos-venda.png",
    "detailUrl": "itens/p26-pedido-de-avaliacao-e-depoimento/",
    "checkoutUrl": null
  },
  {
    "id": "27",
    "title": "Indicação com contexto",
    "family": "Pós-venda e relacionamento",
    "familyKey": "pos-venda",
    "price": 47,
    "delivery": "Roteiros e controle de indicações, com condições claras quando houver benefício",
    "buyer": "negócio que já possui clientes e quer cuidar da continuidade",
    "image": "assets/05-pos-venda.png",
    "detailUrl": "itens/p27-indicacao-com-contexto/",
    "checkoutUrl": null
  },
  {
    "id": "28",
    "title": "Recompra no momento adequado",
    "family": "Pós-venda e relacionamento",
    "familyKey": "pos-venda",
    "price": 37,
    "delivery": "Matriz de ocasião de retorno, elegibilidade, exclusões e mensagens pertinentes",
    "buyer": "negócio que já possui clientes e quer cuidar da continuidade",
    "image": "assets/05-pos-venda.png",
    "detailUrl": "itens/p28-recompra-no-momento-adequado/",
    "checkoutUrl": null
  },
  {
    "id": "29",
    "title": "Renovação de planos e serviços",
    "family": "Pós-venda e relacionamento",
    "familyKey": "pos-venda",
    "price": 47,
    "delivery": "Calendário de vencimentos e mensagens que esclarecem continuidade, condições e decisão",
    "buyer": "negócio que já possui clientes e quer cuidar da continuidade",
    "image": "assets/05-pos-venda.png",
    "detailUrl": "itens/p29-renovacao-de-planos-e-servicos/",
    "checkoutUrl": null
  },
  {
    "id": "30",
    "title": "Retorno de clientes inativos",
    "family": "Pós-venda e relacionamento",
    "familyKey": "pos-venda",
    "price": 37,
    "delivery": "Quadro de motivos de afastamento e abordagens específicas de reconexão",
    "buyer": "negócio que já possui clientes e quer cuidar da continuidade",
    "image": "assets/05-pos-venda.png",
    "detailUrl": "itens/p30-retorno-de-clientes-inativos/",
    "checkoutUrl": null
  },
  {
    "id": "31",
    "title": "Follow-up com próximo passo",
    "family": "Ferramentas comerciais",
    "familyKey": "ferramentas-comerciais",
    "price": 67,
    "delivery": "Quadro com responsável, contexto, próxima ação, prazo e motivo de encerramento",
    "buyer": "dono, autônomo ou gestor de pequena equipe",
    "image": "assets/06-ferramentas-comerciais.png",
    "detailUrl": "itens/p31-follow-up-com-proximo-passo/",
    "checkoutUrl": null
  },
  {
    "id": "32",
    "title": "Venda rastreável no WhatsApp",
    "family": "Ferramentas comerciais",
    "familyKey": "ferramentas-comerciais",
    "price": 37,
    "delivery": "Registro de origem, oportunidade, venda e perda, preservando origem desconhecida",
    "buyer": "dono, autônomo ou gestor de pequena equipe",
    "image": "assets/06-ferramentas-comerciais.png",
    "detailUrl": "itens/p32-venda-rastreavel-no-whatsapp/",
    "checkoutUrl": null
  },
  {
    "id": "33",
    "title": "Calculadora de desconto",
    "family": "Ferramentas comerciais",
    "familyKey": "ferramentas-comerciais",
    "price": 47,
    "delivery": "Simulador do efeito de diferentes descontos sobre contribuição, usando custos informados",
    "buyer": "dono, autônomo ou gestor de pequena equipe",
    "image": "assets/06-ferramentas-comerciais.png",
    "detailUrl": "itens/p33-calculadora-de-desconto/",
    "checkoutUrl": null
  },
  {
    "id": "34",
    "title": "Calculadora de combos",
    "family": "Ferramentas comerciais",
    "familyKey": "ferramentas-comerciais",
    "price": 67,
    "delivery": "Comparação de itens avulsos e pacotes com preço, custo e contribuição estimada",
    "buyer": "dono, autônomo ou gestor de pequena equipe",
    "image": "assets/06-ferramentas-comerciais.png",
    "detailUrl": "itens/p34-calculadora-de-combos/",
    "checkoutUrl": null
  },
  {
    "id": "35",
    "title": "Planejador de capacidade e metas",
    "family": "Ferramentas comerciais",
    "familyKey": "ferramentas-comerciais",
    "price": 47,
    "delivery": "Simulação de atendimentos, capacidade, valor médio e cenários de conversão informados pelo usuário",
    "buyer": "dono, autônomo ou gestor de pequena equipe",
    "image": "assets/06-ferramentas-comerciais.png",
    "detailUrl": "itens/p35-planejador-de-capacidade-e-metas/",
    "checkoutUrl": null
  },
  {
    "id": "36",
    "title": "Painel comercial da semana",
    "family": "Ferramentas comerciais",
    "familyKey": "ferramentas-comerciais",
    "price": 47,
    "delivery": "Resumo de oportunidades, vendas, perdas e ações, com roteiro de reunião curta",
    "buyer": "dono, autônomo ou gestor de pequena equipe",
    "image": "assets/06-ferramentas-comerciais.png",
    "detailUrl": "itens/p36-painel-comercial-da-semana/",
    "checkoutUrl": null
  },
  {
    "id": "37",
    "title": "Primeira semana do vendedor",
    "family": "Treinamento e padrão",
    "familyKey": "treinamento",
    "price": 67,
    "delivery": "Plano diário de aprendizagem, exercícios e critérios de prontidão para atender",
    "buyer": "dono ou líder que precisa orientar vendedores",
    "image": "assets/07-treinamento.png",
    "detailUrl": "itens/p37-primeira-semana-do-vendedor/",
    "checkoutUrl": null
  },
  {
    "id": "38",
    "title": "Simulações de conversas comerciais",
    "family": "Treinamento e padrão",
    "familyKey": "treinamento",
    "price": 47,
    "delivery": "Casos fictícios para praticar atendimento e ficha de observação com exemplos comentados",
    "buyer": "dono ou líder que precisa orientar vendedores",
    "image": "assets/07-treinamento.png",
    "detailUrl": "itens/p38-simulacoes-de-conversas-comerciais/",
    "checkoutUrl": null
  },
  {
    "id": "39",
    "title": "Revisão de conversas pelo gestor",
    "family": "Treinamento e padrão",
    "familyKey": "treinamento",
    "price": 67,
    "delivery": "Rubrica simples de clareza, contexto, informação correta e próximo passo",
    "buyer": "dono ou líder que precisa orientar vendedores",
    "image": "assets/07-treinamento.png",
    "detailUrl": "itens/p39-revisao-de-conversas-pelo-gestor/",
    "checkoutUrl": null
  },
  {
    "id": "40",
    "title": "Passagem de atendimento sem repetir perguntas",
    "family": "Treinamento e padrão",
    "familyKey": "treinamento",
    "price": 67,
    "delivery": "Ficha de transferência com histórico resumido, pendência, responsável e próxima ação",
    "buyer": "dono ou líder que precisa orientar vendedores",
    "image": "assets/07-treinamento.png",
    "detailUrl": "itens/p40-passagem-de-atendimento-sem-repetir-perguntas/",
    "checkoutUrl": null
  },
  {
    "id": "41",
    "title": "Manual de atendimento da empresa",
    "family": "Treinamento e padrão",
    "familyKey": "treinamento",
    "price": 47,
    "delivery": "Modelo editável de responsabilidades, tom, informações aprovadas e encaminhamentos",
    "buyer": "dono ou líder que precisa orientar vendedores",
    "image": "assets/07-treinamento.png",
    "detailUrl": "itens/p41-manual-de-atendimento-da-empresa/",
    "checkoutUrl": null
  },
  {
    "id": "42",
    "title": "Organização do WhatsApp Business",
    "family": "Treinamento e padrão",
    "familyKey": "treinamento",
    "price": 67,
    "delivery": "Tutorial de configuração dos recursos disponíveis, checklist e exemplos de organização; revisar versão antes de produzir",
    "buyer": "dono ou líder que precisa orientar vendedores",
    "image": "assets/07-treinamento.png",
    "detailUrl": "itens/p42-organizacao-do-whatsapp-business/",
    "checkoutUrl": null
  },
  {
    "id": "43",
    "title": "Proposta de automação com escopo fechado",
    "family": "Implantação de IA",
    "familyKey": "implantacao-ia",
    "price": 27,
    "delivery": "Proposta preenchível com entregas, exclusões, responsabilidades e marcos",
    "buyer": "freelancer, consultor ou pequena agência de automação",
    "image": "assets/08-implantacao-ia.png",
    "detailUrl": "itens/p43-proposta-de-automacao-com-escopo-fechado/",
    "checkoutUrl": null
  },
  {
    "id": "44",
    "title": "Calculadora de setup e mensalidade",
    "family": "Implantação de IA",
    "familyKey": "implantacao-ia",
    "price": 67,
    "delivery": "Planilha de trabalho inicial, consumo, suporte e cenários de contribuição",
    "buyer": "freelancer, consultor ou pequena agência de automação",
    "image": "assets/08-implantacao-ia.png",
    "detailUrl": "itens/p44-calculadora-de-setup-e-mensalidade/",
    "checkoutUrl": null
  },
  {
    "id": "45",
    "title": "Briefing de projeto de IA",
    "family": "Implantação de IA",
    "familyKey": "implantacao-ia",
    "price": 67,
    "delivery": "Formulário de descoberta, mapa de processos e critérios para avaliar viabilidade",
    "buyer": "freelancer, consultor ou pequena agência de automação",
    "image": "assets/08-implantacao-ia.png",
    "detailUrl": "itens/p45-briefing-de-projeto-de-ia/",
    "checkoutUrl": null
  },
  {
    "id": "46",
    "title": "Onboarding de implantação",
    "family": "Implantação de IA",
    "familyKey": "implantacao-ia",
    "price": 47,
    "delivery": "Checklist de dependências, responsáveis, validação por etapa e passagem de operação",
    "buyer": "freelancer, consultor ou pequena agência de automação",
    "image": "assets/08-implantacao-ia.png",
    "detailUrl": "itens/p46-onboarding-de-implantacao/",
    "checkoutUrl": null
  },
  {
    "id": "47",
    "title": "Demonstração que explica o projeto",
    "family": "Implantação de IA",
    "familyKey": "implantacao-ia",
    "price": 97,
    "delivery": "Roteiro de apresentação com cenário, evidência do funcionamento e limites do escopo",
    "buyer": "freelancer, consultor ou pequena agência de automação",
    "image": "assets/08-implantacao-ia.png",
    "detailUrl": "itens/p47-demonstracao-que-explica-o-projeto/",
    "checkoutUrl": null
  },
  {
    "id": "48",
    "title": "Entrega e manutenção de agentes",
    "family": "Implantação de IA",
    "familyKey": "implantacao-ia",
    "price": 97,
    "delivery": "Modelo de documentação final, registro de alterações, aceite e definição de atendimento de suporte",
    "buyer": "freelancer, consultor ou pequena agência de automação",
    "image": "assets/08-implantacao-ia.png",
    "detailUrl": "itens/p48-entrega-e-manutencao-de-agentes/",
    "checkoutUrl": null
  }
];
